version: 1.0.{build}
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
nuget:
  project_feed: true
before_build:
- cmd: cd .\src && nuget restore && cd InstaSqlite.Portable && dotnet build
build:
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  verbosity: minimal
after_build:
- cmd: cd .\src && cd .\InstaSqlite.Portable && nuget pack